version: '3.8'

services:
  js:
    build: .
    image: pdf-qrcode:dev-js
    command: bash -lc "cd /app/js && npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/workspace:cached
    environment:
      - NODE_ENV=development

  wasm:
    build: .
    image: pdf-qrcode:dev-wasm
    command: bash -lc "cd /app/wasm && npm ci && (cd packages/wasm-qrcode && wasm-pack build --target web --out-dir ../pkg || true) && npm run dev -- --host 0.0.0.0 --port 5174"
    ports:
      - "5174:5174"
    volumes:
      - ./:/workspace:cached
    environment:
      - NODE_ENV=development
